proxy:
  image: amouat/proxy:1.0
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=(your host's ip address)
    - NGINX_PROXY=http://identidock:9090
  log_driver: syslog
  log_opt:
    tag: docker/{{.ImageName}}/{{.Name}}/{{.ID}}

identidock:
  image: amouat/identidock:1.0
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD
  log_driver: syslog
  log_opt:
    tag: docker/{{.ImageName}}/{{.Name}}/{{.ID}}

dnmonster:
  image: amouat/dnmonster:1.0
  log_driver: syslog
  log_opt:
    tag: docker/{{.ImageName}}/{{.Name}}/{{.ID}}

redis:
  image: redis:4.0
  log_driver: syslog
  log_opt:
    tag: docker/{{.ImageName}}/{{.Name}}/{{.ID}}

logstash:
  image: logstash:2.4.1
  volumes:
    - /logstash.conf:/etc/logstash.conf
  environment:
    LOGSPOUT: ignore
  links:
    - elasticsearch
  ports:
    - "127.0.0.1:5544:5544"
  command: -f /etc/logstash.conf
  log_driver: json-file

elasticsearch:
  image: elasticsearch:2.4.6
  environment:
    LOGSPOUT: ignore
  log_driver: json-file

kibana:
  image: kibana:4
  environment:
    LOGSPOUT: ignore
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "5601:5601"
